In [1]:
from protopop.cluster import Cluster
from astropy import units as u
import numpy as np
cl_ca = Cluster(distance=5.4 * u.kpc, timescale=1 * u.Myr, mass=3e2*u.Msun, history='ca', efficiency=100 )



Setting up...
Calculating initial conditions...
Sampling members...
Total mass is 300.259 (limit was 300)


In [2]:

sample_time = 0.25*u.Myr


In [3]:
sample_ap = np.array([600])*u.AU
sample_wavs = np.array([1.62, 2.10, 3.60, 4.80])*u.um
flux_ca = cl_ca.sample_flux(sample_time, wav=sample_wavs, ap=sample_ap)


  0%|          | 0/359 [00:00<?, ?it/s]

/blue/adamginsburg/t.yoo/from_red/miniconda3/envs/py311/lib/python3.11/site-packages/astropy/units/quantity.py:653: RuntimeWarning: overflow encountered in expm1
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
/blue/adamginsburg/t.yoo/from_red/miniconda3/envs/py311/lib/python3.11/site-packages/astropy/units/quantity.py:653: RuntimeWarning: overflow encountered in multiply
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
/blue/adamginsburg/t.yoo/from_red/miniconda3/envs/py311/lib/python3.11/site-packages/astropy/units/quantity.py:653: RuntimeWarning: overflow encountered in expm1
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
/blue/adamginsburg/t.yoo/from_red/miniconda3/envs/py311/lib/python3.11/site-packages/astropy/units/quantity.py:653: RuntimeWarning: overflow encountered in multiply
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
  0%|          | 1/359 [00:02<16:47,  2.81s/it]/blue/adamg

In [4]:
ev_table = cl_ca.sample_ev(sample_time)


  0%|          | 0/359 [00:00<?, ?it/s]/blue/adamginsburg/t.yoo/from_red/miniconda3/envs/py311/lib/python3.11/site-packages/astropy/units/quantity.py:653: RuntimeWarning: overflow encountered in expm1
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
/blue/adamginsburg/t.yoo/from_red/miniconda3/envs/py311/lib/python3.11/site-packages/astropy/units/quantity.py:653: RuntimeWarning: overflow encountered in multiply
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
  0%|          | 1/359 [00:03<18:27,  3.09s/it]/blue/adamginsburg/t.yoo/from_red/miniconda3/envs/py311/lib/python3.11/site-packages/astropy/units/quantity.py:653: RuntimeWarning: overflow encountered in expm1
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
/blue/adamginsburg/t.yoo/from_red/miniconda3/envs/py311/lib/python3.11/site-packages/astropy/units/quantity.py:653: RuntimeWarning: overflow encountered in multiply
  result = super().__array_ufunc__(function,

/blue/adamginsburg/t.yoo/from_red/miniconda3/envs/py311/lib/python3.11/site-packages/astropy/units/quantity.py:653: RuntimeWarning: overflow encountered in expm1
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
/blue/adamginsburg/t.yoo/from_red/miniconda3/envs/py311/lib/python3.11/site-packages/astropy/units/quantity.py:653: RuntimeWarning: overflow encountered in multiply
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
  2%|▏         | 7/359 [00:22<18:34,  3.17s/it]/blue/adamginsburg/t.yoo/from_red/miniconda3/envs/py311/lib/python3.11/site-packages/astropy/units/quantity.py:653: RuntimeWarning: overflow encountered in expm1
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
/blue/adamginsburg/t.yoo/from_red/miniconda3/envs/py311/lib/python3.11/site-packages/astropy/units/quantity.py:653: RuntimeWarning: overflow encountered in multiply
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
  2%|▏     

In [5]:
print(flux_ca)
print(ev_table)
print(flux_ca[:,0])

[[5.90761937e-05 3.07738213e-05 8.05130107e-06 2.71020005e-06]
 [1.90405962e-02 1.40569682e-02 1.03126493e-02 7.17685101e-03]
 [1.70143522e-03 1.29914125e-03 1.51901262e-03 1.59726964e-03]
 ...
 [2.90851777e-02 1.98136087e-02 1.37332842e-02 1.90962776e-02]
 [6.81082314e+00 7.59770233e+00 7.49496573e+00 5.86403383e+00]
 [8.15402556e+00 9.69834289e+00 9.75612471e+00 6.76308689e+00]] mJy
        Time            Stellar_Mass     ... Stage Stellar_Temperature
------------------- -------------------- ... ----- -------------------
 0.2157553918548939  0.05931884238689196 ...   0.0                 nan
 0.2157553918548939   0.0597884960531208 ...   0.0                 nan
 0.2157553918548939 0.059833938012115076 ...   0.0                 nan
 0.2157553918548939 0.060059521220584965 ...   0.0                 nan
 0.2157553918548939  0.06030855251969202 ...   0.0                 nan
 0.2157553918548939  0.06041681214580022 ...   0.0                 nan
 0.2157553918548939  0.06049817367601129 ...

In [ ]:
from astropy.io import fits
from astropy.wcs import WCS
from astroquery.svo_fps import SvoFps
from astropy import units as u
import matplotlib.pyplot as plt
image_filenames ={
    "f140m": "/orange/adamginsburg/jwst/w51/images/jw06151-o001_t001_nircam_clear-f140m-merged_i2d.fits",
    "f162m": "/orange/adamginsburg/jwst/w51/images/jw06151-o001_t001_nircam_clear-f162m-merged_i2d.fits",
    "f182m": "/orange/adamginsburg/jwst/w51/images/jw06151-o001_t001_nircam_clear-f182m-merged_i2d.fits",
    "f187n": "/orange/adamginsburg/jwst/w51/images/jw06151-o001_t001_nircam_clear-f187n-merged_i2d.fits",
    "f210m": "/orange/adamginsburg/jwst/w51/images/jw06151-o001_t001_nircam_clear-f210m-merged_i2d.fits",
    "f335m": "/orange/adamginsburg/jwst/w51/images/jw06151-o001_t001_nircam_clear-f335m-merged_i2d.fits",
    "f360m": "/orange/adamginsburg/jwst/w51/images/jw06151-o001_t001_nircam_clear-f360m-merged_i2d.fits",
    "f405n": "/orange/adamginsburg/jwst/w51/images/jw06151-o001_t001_nircam_clear-f405n-merged_i2d.fits",
    "f410m": "/orange/adamginsburg/jwst/w51/images/jw06151-o001_t001_nircam_clear-f410m-merged_i2d.fits", # weird, the filename is different from what is downloaded with the STScI pipeline...
    "f480m": "/orange/adamginsburg/jwst/w51/images/jw06151-o001_t001_nircam_clear-f480m-merged_i2d.fits",
    "f560w": "/orange/adamginsburg/jwst/w51/F560W/pipeline/jw06151-o002_t001_miri_f560w_i2d.fits",
    "f770w": "/orange/adamginsburg/jwst/w51/F770W/pipeline/jw06151-o002_t001_miri_f770w_i2d.fits",
    "f1000w": "/orange/adamginsburg/jwst/w51/F1000W/pipeline/jw06151-o002_t001_miri_f1000w_i2d.fits",
    "f1280w": "/orange/adamginsburg/jwst/w51/F1280W/pipeline/jw06151-o002_t001_miri_f1280w_i2d.fits",
    "f2100w": "/orange/adamginsburg/jwst/w51/F2100W/pipeline/jw06151-o002_t001_miri_f2100w_i2d.fits",
    
}


f140m_header = fits.getheader(image_filenames['f140m'], ext=('SCI', 1))
f162m_header = fits.getheader(image_filenames['f162m'], ext=('SCI', 1))
f182m_header = fits.getheader(image_filenames['f182m'], ext=('SCI', 1))
f210m_header = fits.getheader(image_filenames['f210m'], ext=('SCI', 1))
f335m_header = fits.getheader(image_filenames['f335m'], ext=('SCI', 1))
f360m_header = fits.getheader(image_filenames['f360m'], ext=('SCI', 1))
f405n_header = fits.getheader(image_filenames['f405n'], ext=('SCI', 1))
f410m_header = fits.getheader(image_filenames['f410m'], ext=('SCI', 1))
f480m_header = fits.getheader(image_filenames['f480m'], ext=('SCI', 1))
f560w_header = fits.getheader(image_filenames['f560w'], ext=('SCI', 1))
f770w_header = fits.getheader(image_filenames['f770w'], ext=('SCI', 1))
f1000w_header = fits.getheader(image_filenames['f1000w'], ext=('SCI', 1))
f1280w_header = fits.getheader(image_filenames['f1280w'], ext=('SCI', 1))
f2100w_header = fits.getheader(image_filenames['f2100w'], ext=('SCI', 1))
def get_mag(flux, ww, filtername='f140m' ):
   # print(ww.proj_plane_pixel_area())
    
    #flux= (catalog['flux_fit_' + filtername] * u.MJy/u.sr * ww.proj_plane_pixel_area()).to(u.Jy)
    #eflux_jy = (catalog['flux_err_' + filtername] * u.MJy/u.sr *  ww.proj_plane_pixel_area()).to(u.Jy)

    jfilts = SvoFps.get_filter_list('JWST')
    jfilts.add_index('filterID')
    wav = int(filtername[1:-1])

    zeropoint_ab = 3631 * u.Jy  # Default to AB magnitude zero point
 
    if wav < 500:

        zeropoint_vega = u.Quantity(jfilts.loc[f'JWST/NIRCam.{filtername.upper()}']['ZeroPoint'], u.Jy)
    else:
        zeropoint_vega = u.Quantity(jfilts.loc[f'JWST/MIRI.{filtername.upper()}']['ZeroPoint'], u.Jy)
   
    abmag = -2.5 * np.log10(flux / zeropoint_ab) * u.mag
    #abmag_err = 2.5 / np.log(10) * np.abs(eflux_jy / flux) * u.mag

    vegamag = -2.5 * np.log10(flux / zeropoint_vega) * u.mag
    #vegamag_err = 2.5 / np.log(10) * np.abs(eflux_jy / flux) * u.mag

    return  vegamag

f162m_mag = get_mag(flux_ca[:,0].to(u.Jy), WCS(f162m_header), filtername='f162m')
f210m_mag = get_mag(flux_ca[:,1].to(u.Jy), WCS(f210m_header), filtername='f210m')
f360m_mag = get_mag(flux_ca[:,2].to(u.Jy), WCS(f360m_header), filtername='f360m')
f480m_mag = get_mag(flux_ca[:,3].to(u.Jy), WCS(f480m_header), filtername='f480m')
print(f162m_mag, f210m_mag, f360m_mag, f480m_mag)
fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111)
ax.scatter(f162m_mag- f210m_mag, f360m_mag- f480m_mag, c='blue', s=1, label='Cluster')

